version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-nodebb-test
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    restart: always
    volumes:
      - mongodata:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo/mongod.conf:/etc/mongod.conf:ro

  # nodebb:
  #   image: nodecustom
  #   container_name: nodebb-test
  #   ports:
  #     - 4567:4567
  #   restart: always
  #   depends_on:
  #     - mongo

volumes:
  mongodata:
